routingRules:
  - version: "2.0.0"
    targetType: "bpp"
    endpoints:
      - confirm
      - status

  - version: "2.0.0"
    targetType: "url"
    target:
      url: "https://34.93.141.21.sslip.io/beckn"
    endpoints:
      - discover
